//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanPizza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPizza
    {
        public int PizzaID { get; set; }
        public Nullable<bool> Salami { get; set; }
        public Nullable<bool> Ham { get; set; }
        public Nullable<bool> Kulen { get; set; }
        public Nullable<bool> Ketchup { get; set; }
        public Nullable<bool> Mayonnaise { get; set; }
        public Nullable<bool> HotPepper { get; set; }
        public Nullable<bool> Olives { get; set; }
        public Nullable<bool> Oregano { get; set; }
        public Nullable<bool> Sesame { get; set; }
        public Nullable<bool> Cheese { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual tblSize tblSize { get; set; }
    }
}
